Main Group 2 - Requisitos 60, 61, 62 e 63
tryber/sd-010-a-project-recipes-app pull request #458
Opened 2021-07-06 17:03 UTC by mateus2a

2021-07-06 23:11 UTC, gabriellferreira-dev commented on src/pages/ExploreByOrigin/index.js
> +      <Header title="Explorar por Origem" />
O teste busca por "Explorar Origem", então sugiro alterar o titulo no Header.

2021-07-06 23:15 UTC, gabriellferreira-dev requested changes
Deixei uma observação no arquivo ExploreByOrigin.

2021-07-06 23:20 UTC, mateus2a commented on src/pages/ExploreByOrigin/index.js
> +      <Header title="Explorar por Origem" />
Boaa, acabei de mandar as alterações : )

2021-07-07 20:53 UTC, gabriellferreira-dev approved these changes

2021-07-07 21:22 UTC, Gui-lira approved these changes

2021-07-07 21:25 UTC, merged