[GRUPO 21] (Tela Explorar comidas ou bebidas) Adiciona a telas com links para explorar.
tryber/sd-010-a-project-recipes-app pull request #799
Opened 2021-07-12 18:46 UTC by edersonrdg

- [ ] requisito 70
- [ ] requisito 71
- [ ] requisito 72
- [ ] requisito 73
- [ ] requisito 74

2021-07-12 19:31 UTC, carlos25xrm approved these changes

2021-07-12 19:59 UTC, nascjoao requested changes
A aplicação está com um comportamento inesperado.
A rota "/explorar" retorna um erro e quebra.

2021-07-14 19:03 UTC, edersonrdg commented
> A aplicação está com um comportamento inesperado.
> A rota "/explorar" retorna um erro e quebra.

2021-07-14 19:58 UTC, nascjoao approved these changes

2021-07-14 19:58 UTC, merged